package tn.enicar.projet.model;
// Generated 15 janv. 2016 00:46:30 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "ETUDIANT")
public class Etudiant implements java.io.Serializable {

	private String email;
	private String idetud;
	private String adretud;
	private Date datenaissance;
	private String niveauetud;
	private String nometud;
	private String prenometud;
	private String specialite;
	private String tel;
	private String universite;

	public Etudiant() {
	}

	public Etudiant(String email, String nometud, String prenometud) {
		this.email = email;
		this.nometud = nometud;
		this.prenometud = prenometud;
	}

	public Etudiant(String email, String idetud, String adretud, Date datenaissance, String niveauetud, String nometud,
			String prenometud, String specialite, String tel, String universite) {
		this.email = email;
		this.idetud = idetud;
		this.adretud = adretud;
		this.datenaissance = datenaissance;
		this.niveauetud = niveauetud;
		this.nometud = nometud;
		this.prenometud = prenometud;
		this.specialite = specialite;
		this.tel = tel;
		this.universite = universite;
	}

	@Id

	@Column(name = "EMAIL", unique = true, nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "IDETUD", length = 0)
	public String getIdetud() {
		return this.idetud;
	}

	public void setIdetud(String idetud) {
		this.idetud = idetud;
	}

	@Column(name = "ADRETUD", length = 20)
	public String getAdretud() {
		return this.adretud;
	}

	public void setAdretud(String adretud) {
		this.adretud = adretud;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAISSANCE", length = 7)
	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	@Column(name = "NIVEAUETUD", length = 20)
	public String getNiveauetud() {
		return this.niveauetud;
	}

	public void setNiveauetud(String niveauetud) {
		this.niveauetud = niveauetud;
	}

	@Column(name = "NOMETUD", nullable = false, length = 20)
	public String getNometud() {
		return this.nometud;
	}

	public void setNometud(String nometud) {
		this.nometud = nometud;
	}

	@Column(name = "PRENOMETUD", nullable = false, length = 20)
	public String getPrenometud() {
		return this.prenometud;
	}

	public void setPrenometud(String prenometud) {
		this.prenometud = prenometud;
	}

	@Column(name = "SPECIALITE", length = 20)
	public String getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(String specialite) {
		this.specialite = specialite;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "UNIVERSITE", length = 20)
	public String getUniversite() {
		return this.universite;
	}

	public void setUniversite(String universite) {
		this.universite = universite;
	}

}
