package tn.enicar.projet.model;
// Generated 15 janv. 2016 00:46:30 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prof generated by hbm2java
 */
@Entity
@Table(name = "PROF")
public class Prof implements java.io.Serializable {

	private String idprof;
	private String email;
	private Date datenaissance;
	private String nomprof;
	private String prenomprof;
	private String adrprof;
	private String specialite;
	private String tel;
	private String titre;
	private String universite;

	public Prof() {
	}

	public Prof(String idprof, String email, String nomprof, String prenomprof) {
		this.idprof = idprof;
		this.email = email;
		this.nomprof = nomprof;
		this.prenomprof = prenomprof;
	}

	public Prof(String idprof, String email, Date datenaissance, String nomprof, String prenomprof, String adrprof,
			String specialite, String tel, String titre, String universite) {
		this.idprof = idprof;
		this.email = email;
		this.datenaissance = datenaissance;
		this.nomprof = nomprof;
		this.prenomprof = prenomprof;
		this.adrprof = adrprof;
		this.specialite = specialite;
		this.tel = tel;
		this.titre = titre;
		this.universite = universite;
	}

	@Id

	@Column(name = "IDPROF", unique = true, nullable = false, length = 20)
	public String getIdprof() {
		return this.idprof;
	}

	public void setIdprof(String idprof) {
		this.idprof = idprof;
	}

	@Column(name = "EMAIL", nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAISSANCE", length = 7)
	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	@Column(name = "NOMPROF", nullable = false, length = 20)
	public String getNomprof() {
		return this.nomprof;
	}

	public void setNomprof(String nomprof) {
		this.nomprof = nomprof;
	}

	@Column(name = "PRENOMPROF", nullable = false, length = 20)
	public String getPrenomprof() {
		return this.prenomprof;
	}

	public void setPrenomprof(String prenomprof) {
		this.prenomprof = prenomprof;
	}

	@Column(name = "ADRPROF", length = 20)
	public String getAdrprof() {
		return this.adrprof;
	}

	public void setAdrprof(String adrprof) {
		this.adrprof = adrprof;
	}

	@Column(name = "SPECIALITE", length = 20)
	public String getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(String specialite) {
		this.specialite = specialite;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "TITRE", length = 20)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "UNIVERSITE", length = 20)
	public String getUniversite() {
		return this.universite;
	}

	public void setUniversite(String universite) {
		this.universite = universite;
	}

}
